USE [master]
GO
/****** Object:  Database [LandAssets]    Script Date: 2015/8/26 下午 05:13:13 ******/
CREATE DATABASE [LandAssets]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LandAssets', FILENAME = N'd:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\LandAssets.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LandAssets_log', FILENAME = N'd:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\LandAssets_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [LandAssets] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LandAssets].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LandAssets] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LandAssets] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LandAssets] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LandAssets] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LandAssets] SET ARITHABORT OFF 
GO
ALTER DATABASE [LandAssets] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LandAssets] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LandAssets] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LandAssets] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LandAssets] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LandAssets] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LandAssets] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LandAssets] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LandAssets] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LandAssets] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LandAssets] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LandAssets] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LandAssets] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LandAssets] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LandAssets] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LandAssets] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LandAssets] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LandAssets] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LandAssets] SET  MULTI_USER 
GO
ALTER DATABASE [LandAssets] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LandAssets] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LandAssets] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LandAssets] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [LandAssets]
GO
/****** Object:  Table [dbo].[LandsBefore]    Script Date: 2015/8/26 下午 05:13:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LandsBefore](
	[NoA] [char](4) NOT NULL,
	[NoB] [nchar](4) NOT NULL,
	[NoC] [char](4) NOT NULL,
	[RegisterNo] [char](7) NULL,
	[RegisterDate] [date] NULL,
	[RegisterReasonId] [int] NULL,
	[LandTypeId] [int] NULL,
	[LandArea] [float] NULL,
	[CurrentValue] [int] NULL,
	[AnnourceValue] [int] NULL,
	[Timestamp] [timestamp] NOT NULL,
 CONSTRAINT [PK_LandsBefore] PRIMARY KEY CLUSTERED 
(
	[NoA] ASC,
	[NoB] ASC,
	[NoC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LandTypes]    Script Date: 2015/8/26 下午 05:13:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LandTypes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Type] [nvarchar](50) NOT NULL,
	[Timestamp] [timestamp] NOT NULL,
 CONSTRAINT [PK_LandTypes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[RegisterReasonTypes]    Script Date: 2015/8/26 下午 05:13:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RegisterReasonTypes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Reason] [nvarchar](50) NOT NULL,
	[Timestamp] [timestamp] NOT NULL,
 CONSTRAINT [PK_RegisterReasonTypes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[LandsBefore]  WITH CHECK ADD  CONSTRAINT [FK_LandsBefore_LandTypes] FOREIGN KEY([LandTypeId])
REFERENCES [dbo].[LandTypes] ([Id])
GO
ALTER TABLE [dbo].[LandsBefore] CHECK CONSTRAINT [FK_LandsBefore_LandTypes]
GO
ALTER TABLE [dbo].[LandsBefore]  WITH CHECK ADD  CONSTRAINT [FK_LandsBefore_RegisterReasonTypes] FOREIGN KEY([RegisterReasonId])
REFERENCES [dbo].[RegisterReasonTypes] ([Id])
GO
ALTER TABLE [dbo].[LandsBefore] CHECK CONSTRAINT [FK_LandsBefore_RegisterReasonTypes]
GO
USE [master]
GO
ALTER DATABASE [LandAssets] SET  READ_WRITE 
GO
