//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandAssets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandsBefore
    {
        public string NoA { get; set; }
        public string NoB { get; set; }
        public string NoC { get; set; }
        public string RegisterNo { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<int> RegisterReasonId { get; set; }
        public Nullable<int> LandTypeId { get; set; }
        public Nullable<double> LandArea { get; set; }
        public Nullable<int> CurrentValue { get; set; }
        public Nullable<int> AnnourceValue { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual RegisterReasonType RegisterReasonType { get; set; }
        public virtual LandType LandType { get; set; }
    }
}
